name: Build and deploy workflow

on:
  push:
    branches:
      - dev
      - master
      - 'release/**'
#      - 'hotfix/**'
#      - 'feature/**'

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: ${{ secrets.BOT_NAME }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Publish to Docker Hub
#        if: "startsWith(env.TAG_NAME, 'dev') || startsWith(env.TAG_NAME, 'release')"
        run: >-
          mvn 
          clean install
          -PpushToDocker         

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Push image to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run:
          docker pull atmtrans/busbot &&
          docker tag atmtrans/busbot registry.heroku.com/atmtrans/busbot &&
          docker push registry.heroku.com/atmtrans/busbot
      - name: Deploy application to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run:
          heroku container:release -a atmtrans busbot
