name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: ${{secrets.BOT_NAME}}
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      HEROKU_APP_NAME: "busbot-atmtrans"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build Docker image and push to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: my-registry/my-image:latest
          build-args: |
            BOT_NAME= ${{env.BOT_NAME}}
            BOT_TOKEN= ${{env.BOT_TOKEN}}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: youremail@example.com
          docker_image: my-registry/my-image:latest