name: Pull request workflow

on:
  pull_request:
    branches: [ dev, master, release ]

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: ${{ secrets.BOT_NAME }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Publish to Docker Hub
        #        if: "startsWith(env.TAG_NAME, 'dev') || startsWith(env.TAG_NAME, 'release')"
        run: >-
          mvn 
          clean install
